inference:
  task: honeycomb_test_feature2
  images_dir: ./test_images/honeycomb_v3_test
  checkpoint: ./output_checkpoints/honeycomb_data2-epoch-30.pth
  save_result_root: ./test_result
  dinov3_ckpt: ./pretrained_checkpoint/dinov3_convnext_base_pretrain_lvd1689m-801f2ba9.pth

  overlay: true
  save_mask_01: true
  save_comparison: false
  bin_thresh: 0.5

  patch_size: 512
  patch_stride_ratio: 0.66
  infer_batch_size: 16

  output_name_mode: original
  output_prefix: ""
